export enum EOrganizationType {
  ADMIN = 'ADMIN',
  AI_COMPANY = 'AI_COMPANY',
  DISTRIBUTOR = 'DISTRIBUTOR',
  IMAGING_FACILITY = 'IMAGING_FACILITY',
  RADIOLOGY = 'RADIOLOGY',
  SYSTEM = 'SYSTEM',
}
