export enum EPlatformSocketEventType {
  CONFIRM = 'CONFIRM',
  DEVICE_TOKENS_CHANGED = 'DEVICE_TOKENS_CHANGED',
  NEW_TASK = 'NEW_TASK',
  ORGANIZATION_CHANGED = 'ORGANIZATION_CHANGED',
  ORGANIZATION_SETTINGS_CHANGED = 'ORGANIZATION_SETTINGS_CHANGED',
  REFRESH_AGENT_KEY = 'REFRESH_AGENT_KEY',
  UPDATE_PUBLIC_PACS_SERVER_CONFIG = 'UPDATE_PUBLIC_PACS_SERVER_CONFIG',
  USER_CHANGED = 'USER_CHANGED',
}

export enum ERenderSocketEventType {
  ORGANIZATION_CHANGED = 'ORGANIZATION_CHANGED',
  REFRESH_AGENT_KEY = 'REFRESH_AGENT_KEY',
  USER_CHANGED = 'USER_CHANGED',
  HAS_NEW_VERSION = 'HAS_NEW_VERSION',
  UPDATE_PROGRESS = 'UPDATE_PROGRESS',
  CANCEL_UPDATE = 'CANCEL_UPDATE',
}
