export enum ETaskType {
  CHECK_LOCAL_FILE_EXISTENCE = 'CHECK_LOCAL_FILE_EXISTENCE',
  REQUEST_PHI = 'REQUEST_PHI',
  REQUEST_STUDY_NOTES = 'REQUEST_STUDY_NOTES',
  UPDATE_PHI_DATA = 'UPDATE_PHI_DATA',
  SEND_LOCAL_DICOM = 'SEND_LOCAL_DICOM',
  SEND_PLATFORM_DICOM = 'SEND_PLATFORM_DICOM',
  SEND_STUDY_NOTES = 'SEND_STUDY_NOTES',
}

export enum ETaskStatus{
  SUCCESS = 'SUCCESS',
  CONFIRMED = 'CONFIRMED',
  ERROR = 'ERROR',
}
