apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -vvv
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -vvv
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: agent
    spec:
      containers:
        - image: nanoxmarketplace/agent:1.0.0
          name: agent
          ports:
            - containerPort: 3005
            - containerPort: 3006
            - containerPort: 9999
          resources: {}
          volumeMounts:
            - mountPath: /app/data/config.json
              subPath: config.json
              name: agent-config
            - mountPath: /app/data
              name: agent-data
      restartPolicy: Always
      volumes:
        - name: agent-config
          secret:
            items:
              - key: agent-config
                path: config.json
            secretName: agent-config
        - name: agent-data
          persistentVolumeClaim:
            claimName: agent-data
status: {}
