apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -vvv
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
spec:
  type: NodePort
  ports:
    - name: "https"
      port: 3005
      targetPort: 3005
    - name: "http"
      port: 3006
      targetPort: 3006
    - name: "dimse"
      port: 9999
      targetPort: 9999
  selector:
    io.kompose.service: agent
status:
  loadBalancer: {}
