apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: agent-data
  name: agent-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
status: {}
